parameters:
  - name: deployment_name
    type: string
  - name: sample_request
    type: string

steps:
  - task: AzureCLI@2
    displayName: Test deployment
    inputs: 
      azureSubscription: $(ado_service_connection_rg) #needs to have access at the RG level 
      scriptType: bash
      workingDirectory: '$(System.DefaultWorkingDirectory)/data/managed-endpoints'
      scriptLocation: inlineScript
      inlineScript: |
        set -e
        RESPONSE=$(az ml online-endpoint invoke -n $(endpoint_name) --deployment ${{ parameters.deployment_name }} --request-file ${{ parameters.sample_request }})
        echo $RESPONSE
