# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: deployment_name
  type: string
- name: deployment_file
  type: string

steps:
  - task: AzureCLI@2
    displayName: Update deployment
    inputs: 
      azureSubscription: $(ado_service_connection_rg) #needs to have access at the RG level 
      scriptType: bash
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      scriptLocation: inlineScript
      inlineScript: |
        az ml online-deployment update --name ${{ parameters.deployment_name }} --endpoint $(endpoint_name) \
          -f ${{ parameters.deployment_file }}