# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: endpoint_name
  type: string
- name: deployment_name
  type: string
- name: model_name
  type: string
- name: traffic
  type: int

steps:
    
- task: AzureCLI@2
  displayName: Creating online deployment
  inputs:
    azureSubscription: $(ado_service_connection_aml_ws)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      python templates/src/python-sdk-v2/create_online_deployment.py \
        -ne "${{parameters.endpoint_name}}" \
        -nd "${{parameters.deployment_name}}" \
        -nm "${{parameters.model_name}}" \
        -t "${{parameters.traffic}}" \

