# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: endpoint_name
  type: string
- name: deployment_name
  type: string
- name: model_path
  type: string
- name: compute
  type: string
- name: instance_count
  type: string
- name: max_concurrency_per_instance
  type: string
- name: mini_batch_size
  type: string
- name: output_file_name
  type: string

steps:
    
- task: AzureCLI@2
  displayName: Creating online deployment
  inputs:
    azureSubscription: $(ado_service_connection_aml_ws)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      python templates/src/python-sdk-v2/create_batch_deployment.py \
        --endpoint_name "${{parameters.endpoint_name}}" \
        --deployment_name "${{parameters.deployment_name}}" \
        --model_path "${{parameters.model_path}}" \
        --compute "${{parameters.compute}}" \
        --instance_count "${{parameters.instance_count}}" \
        --max_concurrency_per_instance "${{parameters.max_concurrency_per_instance}}" \
        --mini_batch_size "${{parameters.mini_batch_size}}" \
        --output_file_name "${{parameters.output_file_name}}" \



