name: 'YAML Read'
description: 'This is a NodeJS action to read YAML configuation files.'
inputs:
  config:
    description: 'Config file name'
    required: true
    default: ''
outputs:
  resource_group:
    description: 'The resource group the AML workspace is in'
  aml_workspace:
    description: 'The AML workspace'
  bep:
    description: 'The batch endpoint name'
  oep:
    description: 'The online endpoint name'
  terraform_version:
    description: 'Terraform version'
  terraform_workingdir:
    description: 'Terraform State working directory'
  terraform_st_resource_group:
    description: 'Terraform State Resource Group'
runs:
  using: 'node16'
  main: 'index.js'
